-- migrate:up
ALTER TABLE ar_sales
  ADD company_code varchar(10) DEFAULT '',
  ADD gl_account varchar(10) DEFAULT '',
  ADD clearing_date timestamp DEFAULT now(),
  ADD clearing_document varchar(10) DEFAULT '',
  ADD assignment varchar(20) DEFAULT '',
  ADD fiscal_year integer DEFAULT 0,
  ADD document_number varchar(10) NOT NULL,
  ADD line_item integer DEFAULT 0,
  ADD posting_date timestamp DEFAULT now(),
  ADD document_date timestamp NOT NULL,
  ADD currency decimal(15,2) DEFAULT 0.00,
  ADD reference varchar(20) DEFAULT '',
  ADD document_type varchar(10) DEFAULT '',
  ADD posting_period integer DEFAULT 0,
  ADD posting_key varchar(10) DEFAULT '',
  ADD debit_credit varchar(10) DEFAULT '',
  ADD amount_in_local decimal(15,2) DEFAULT 0.00,
  ADD amount decimal(15,2) DEFAULT 0.00,
  ADD text varchar(50) DEFAULT '',
  ADD cost_center varchar(10) DEFAULT '',
  ADD baseline_payment_date timestamp DEFAULT now(),
  ADD open_item varchar(5) DEFAULT '',
  ADD value_date timestamp DEFAULT now(),
  ADD document_status varchar(5) DEFAULT '',
  ADD gl_currency varchar(5) DEFAULT '',
  ADD profit_center varchar(10) DEFAULT '',
  ADD gl_amount decimal(15,2) DEFAULT 0.00,
  ADD clearing_year integer DEFAULT 0,
  DROP COLUMN name, 
  DROP COLUMN address, 
  DROP COLUMN phone 

-- migrate:down